### ISSUE TITLE
깨끗한 코드 - 이영범

### ISSUE THREAD

**Issue by Dev-Beom** [Soongsil-Developers/bookclub-2022-cleancode#1]
# 토막 정리
- 깨끗한 코드를 작성하는 방법은 배우기 어렵다. 단순히 원칙과 패턴을 안다고 깨끗한 코드가 나오지 않는다. 고생을 해야한다. 스스로 연습하고 실패도 맛봐야 한다.
- 쓰레기 코드를 만들어두고, 잘 돌아가니 안도하고 나중에 다시 잘 짜겠다고 하고 보지 않는다. 나중은 결코 오지 않음.
- 나쁜 코드는 개발 속도를 크게 떨어뜨림. 팀 생산성이 떨어짐. 마침내 0에 근접함.
- 시간을 들여 깨끗한 코드를 만드는 노력이 비용을 절감하는 방법일 뿐만 아니라 전문가로서 살아남는 길이다.
- 나쁜 코드의 위험을 이해하지 못하는 관리자 말을 그대로 따르는 행동은 전문가답지 못하다.
- 개발 기한을 맞추는 유일한 방법은, 언제나 코드를 최대한 깨끗하게 유지하는 습관.
- 깨끗한 코드를 작성하는 프로그래머는 빈 캔퍼스를 우아한 작품응로 바꿔가는 화가와 같음.
- 잘 짠 코드가 전부는 아님. 시간이 지나도 언제나 깨끗하게 유지해야 함. 시간이 지나면서 엉망응로 전략하는 코드가 많음. 적극적으로 코드의 퇴보를 막아야 함.
- 체크아웃을 할 때 좀 더 깨끗한 코드를 체크인 한다면 코드는 절대 나빠지지 않음. 한꺼번에 많은 시간과 노력을 투자해 코드를 정리할 필요도 없음. 변수 이름 개선, 함수 분할, 중복 제거, 등 간단한 작업으로 정리해도 충분함

# 생각 정리
오래된 프로젝트의 실무에 투입되어 개발하면서 마음속으로 생각했던 내용들이 누구나 다 비슷한 생각을하고 있었던 것 같다.
개발자로 한번쯤은 들어봤던 유명한 사람들의 의견을 살펴볼 수 있었는데, 공감가는 내용도 있었고, 내가 쓰레기를 팀원들에게 넘겨주고 있었다는 것도 조금... 깨닫게 되었다.
코드를 아름답게 잘 짜는 것은 어려운 것 같다. 1장에선 그림그리는 것에 비유했듯이 나는 재능충이 아니니 열심히 노력해야한다.

**Comment by ing03201** [comment]
확인했습니다! 해당 내용들 중에 다음주 2회차 미팅때 선별해서 넣을게요! 감사합니다!
