### ISSUE TITLE
2주차 2장, 3장 - 주재현

### ISSUE THREAD

**Issue by joojae02** [Soongsil-Developers/bookclub-2022-cleancode#2]
# 2장 의미 있는 이름

- 의도를 분명히 밝혀라
  - 코드의 이해와 변경을 쉽게 함
  - 함축성
 
- 그릇된 정보를 피해라
  - 널리 쓰이는 의미 단어 피하기
  - 약어 피하기

- 의미 있게 구분하라  
  - 읽는 사람이 차이를 알도록 이름 짓기
  - Info, Data 등은 무엇인지 알 수 없음

- 발음하기 쉬운 이름을 사용하라

- 검색하기 쉬운 이름을 사용하라
  - 이름 길이는 범위 크기에 비례해야함

- 인코딩을 피하라
  - 헝가리식 표기법, 접두어 피하기

- 자신의 기억력을 자랑하지 마라
  - 루프 횟수 변수 제외하고는 i, k, j 등 사용금지
  
  - 클래스 이름
    - 명사나 명사구 
    - ex) Customer, WikiPage, Account, AddressParser
    - Info나 Data 처럼 모호한 단어 피하기
  
  - 메소드 이름
    - 동사나 동사구
    - ex) postPayment, deletePage, save
  
  - 접근자, 변경자, 조건자 각각 get, set, is

- 기발한 이름을 피하라
  - 자신만 아는 혹은 특정 집단에서만 사용하는 농담은 피해야함

- 한 개념에 한 단어를 사용하라
  - controller, manager, diver와 같이 같은 의미의 단어여도 하나만 사용해야함 
  - 여러 단어 사용시 혼동하기 쉬움

- 말장난을 하지 마라
  - 한 단어를 두가지 기능으로 사용하지 말아야함
  - 사용하면 코드를 직접 봐야 이해할수 있음

- 해법 영역에서 가져온 이름을 사용하라
  - 전산용어, 알고리즘 이름, 패턴이름, 수학용어
  - 기술 개념에는 기술 이름

- 문제 영역에서 가져온 이름을 사용하라
  - 문제 영역 개념과 관련있다면 문제영역에서 이름을 가져와야 함

- 의미 있는 맥락을 추가하라
  - 클래스, 함수, 이름 공간에 넣어 맥락을 부여 실패한다면 접두어를 붙임

- 불필요한 맥락을 없애라
  - 중복이나 부적절한 이름 빼기 기본적으로 짧은 이름이 긴 이름보다 좋음
  - 단 의미가 분명한 경우에만

-----

# 3장 함수

- 작게 만들어라
  - 함수은 작은게 더 이해하기 쉬움
  - 들여쓰기를 최대한 자제해야함
  - 분기를 적게

- 한가지만 해라
  - 함수는 한가지만 해야함
  - 한가지 기능만을 수행

- 함수당 추상화 수준은 하나로
  - 함수가 한가지 작업만을 하려면 문장의 추상화 수준이 동일해야함
  - 추상화 수준이 섞이면 읽기 어려워짐
  
  - 내려가기 규칙
    - 위에서 아래로 이야기처럼 읽혀야 좋음
    - 한 함수 다음은 추상화 수준이 한단계 낮은 함수 가 오는게 좋음

- Switch 문
  - switch 문을 사용하게되면 분기가 많아지게 됨
  - 한가지 작업만하는 switch문은 만들기 어려움
  - 사용해야 한다면 다형성을 이용하여 사용하는 것이 좋음

- 서술적인 이름을 사용해라
  - 이름이 길어도 괜찮으니 여러 단어를 사용해 기능을 잘 표현하는 이름을 선택해야함

- 함수 인수
  - 함수 인수는 적을수록 좋음

- 단항 함수 
    - 인수에 질문, 이벤트 두 형식 제외하고는 피하는게 좋음
    - 사용하더라도 변환 함수 형식을 따르는 편이 좋음

- 플래그 함수
    - 플래그를 넘기는 함수는 좋지 않음
    - 대신 여러 함수로 나누는게 좋음

- 이항 함수
    - Point 처럼 인수가 2개가 적절한 경우나 어쩔수 없는 경우를 제외하고는 사용하지 않는 편이 좋음

- 삼항 함수
    - 부동 소수점 비교

- 인수 객체
     - 독자적인 클래스 변수로 선언

- 인수 목록
     - 가변 인수는 하나의 리스트로 생각하여 단항, 이항, 삼항 등으로 구분

- 동사와 키워드
    - 단항 함수는 함수와 인자가 동사/명사 쌍
    - 함수 이름에 키워드 추가해 순서 구분

- 부수 효과를 일으키지 마라
  - 한 함수에서 한가지를 하면서 다른 부분에 영향을 끼치지 말아야 함

- 명령과 조회를 분리하라
  - 수행하거나 답하거나 둘중 하나만 해야함
  - 예제 set 처럼 명령이 성공하면 대신 다른 함수로 나누는 것이 좋음

- 오류코드 보다 예외를 사용하라
  - 오류 코드를 반환하는 방식은 명령/조회 분리 규칙을 미묘하게 위반함
  - 오류코드 대신 예외를 사용하면 코드가 깔끔해짐

- try catch 문 뽑아내기
    - try catch문은 한 함수가 성공했을 때 실패 했을 때 두 기능을 함으로 한가지 작업만을 해야하는 규칙으 위반함
    - 정상동작과 오류 처리 동작을 분리하는 것이 좋음

- 오류 처리도 한가지 작업이다
    - 오류 처리도 한가지 작업임으로 오류 처리 함수는 오류만 처리해야함

- 반복하지 마라
  - 중복성을 제거해야함
  - 중복이 된다면 길이가 늘어나고 고치게 된다면 모두 고쳐야 함

- 구조적 프로그래밍
  - 함수는 return문이 하나여야함
  - 루프안에서 break나 continue를 사용해서는 안됨
  - goto는 절대 사용해서는 안됨

**Comment by ing03201** [comment]
확인했습니다! 감사합니다!
