### ISSUE TITLE
의미 있는 이름 - 이영범

### ISSUE THREAD

**Issue by Dev-Beom** [Soongsil-Developers/bookclub-2022-cleancode#3]
# 토막 정리

- 이름을 잘 지으면 여러모로 편하다.
- 의도를 분명히 밝혀라.
- 좋은 이름을 지으려면 시간이 많이 걸리지만 좋은 이름으로 절약하는 시간이 더 많다.
- 그릇된 정보를 피하라. 그릇된 단서는 코드 의미를 흐린다.
- 컴파일러나 인터프리터만 통과하려는 생각으로 코드를 구현하지 마라.
- 발음하기 쉬운 이름을 사용하라.
- 검색하기 쉬운 이름을 사용하라.(여기서 검색은 IDE에서의 검색)
- 인코딩을 피하라.
- 자신의 기억력을 자랑하지 마라. 모두가 이해할 수 있도록 표현하자.
- 클래스 이름과 객체 이름은 명사나 명사구가 적합하다.
- 메서드 이름은 동사나 동사구가 적합하다.
- 기발한 이름은 피하라. 진지하게 작명하자! (+ 말장난 하지 말자.)
- 한 개념에 한 단어를 사용하자.
- 모든 이름을 도메인에서 가져오지 말고, 해법 영역에서 가져온 이름을 사용하자.
- 문제 영역에서 가져온 이름을 사용하자.
- 의미있는 맥락을 추가하자. 클래스, 함수, 이름 공간에 넣어 맥락을 부여하고, 모든 방법이 실패한다면 마지막 수단으로 접두어를 붙이자.
- 맥락을 보고 불필요한 맥락을 없애자.

# 생각 정리

- 맥락과, 문장 혹은 단어의 표현에 대한 내용들로 이번 챕터는 주를 이뤘음.
- 개발은 혼자 하는 것이 아닌 많은 사람들이 함께 하거나 함께 할 수 있다는 것을 명심해야 할 것 같음.
- 내 문서의 의도나 목적이 다른 사람들에게 명확하게 전달 되게끔 매사에 고민해 봐야함.

**Comment by ing03201** [comment]
확인하였습니다! 감사합니다!
